### ISSUE TITLE
About detailed usage of your code

### ISSUE THREAD

**Issue by hthoai** [ShreyasArthur/AbnormalEventDetection#1]
Thank you very much for your work, could you please give me detailed steps for training with your code?!
Your help is appreciated.

**Comment by pseudo-sm** [comment]
I am up for this !! Can I document it?

**Comment by ShreyasArthur** [comment]
> I am up for this !! Can I document it?

Sure we do have paper as well! Check it out! :)
https://www.academia.edu/40286517/Abnormal_Events_Detection_in_Surveillance_Systems
