### ISSUE TITLE
Data collection of links

### ISSUE THREAD

**Issue by ShaoDu** [ShreyasArthur/AbnormalEventDetection#2]
Hello, can you share the data set link? I have been failing to download the official website of UCF. I am a Chinese. If you are also a Chinese, do you have a link address in China

**Comment by ShreyasArthur** [comment]
Have you tried this link? 
https://www.dropbox.com/sh/75v5ehq4cdg5g5g/AABvnJSwZI7zXb8_myBA0CLHa?dl=0
