### ISSUE TITLE
data

### ISSUE THREAD

**Issue by yassinesamet** [ShreyasArthur/AbnormalEventDetection#4]
good job !!!!!!
where can i find the dataset of trining  ??

**Comment by ShreyasArthur** [comment]
Hi! Please, go through our paper to know more about the dataset. The link to our paper is https://www.academia.edu/40286517/Abnormal_Events_Detection_in_Surveillance_Systems

**Comment by yassinesamet** [comment]
@ShreyasArthur did the trainig code work proprely ??

**Comment by yassinesamet** [comment]
@ShreyasArthur  i think there is an error in the training class 
in transforming from byte to string
