### ISSUE TITLE
Error about test detect.py 

### ISSUE THREAD

**Issue by Chuttyboy** [ShreyasArthur/AbnormalEventDetection#5]
Hello @ShreyasArthur 

![1](https://user-images.githubusercontent.com/79959547/130060418-0f66b804-91cf-4ba6-8e27-f1e916ac50ef.png)

How to resolve that?

Thank you

**Comment by sonithshetty** [comment]
did the project run on your computer?

**Comment by Chuttyboy** [comment]
> did the project run on your computer?

No , it didn't work for me.
